export const VALIDATION_ERROR = 'Resolve Validation Error Before Submit!';
export const DELETE_CONFIRMATION_MSG = 'Are you sure you want to delete this item?';
export const OLDPASSWORDWRONG = 'Old Password is Wrong';
export const PASSWORDNOTMATCH = 'New Password and Confirm Password not match';
export const CHANGEPASSWORD = 'Changed Password Successfully';
export const BLOCK_CONFIRMATION_MSG = 'Are you sure you want to block this item?';
export const UNBLOCK_CONFIRMATION_MSG = 'Are you sure you want to unblock this item?';
export const COMTHING_WENTWRONG = 'Something went wrong!!';
export const APPROVE_CONFIRMATION_MSG = 'Are you sure you want to Approve this item?';